; --- UNIVERSAL FILE SETTINGS SHAREABLE ACROSS BOTH ENVS ---
[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit BusIO @ ^1.16.2

; --- TARGET 1: THE STANDARD 38-PIN DEV KIT ---
[env:esp32dev]
platform = espressif32 @ 6.9.0
board = esp32dev
build_src_filter = +<main_devkit.cpp> -<main_xiao_c6.cpp>

; --- TARGET 2: THE SEEED STUDIO XIAO ESP32-C6 ---
[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
build_src_filter = +<main_xiao_c6.cpp> -<main_devkit.cpp>
build_unflags = -std=gnu++2b
build_flags = -std=gnu++2a
